# Generated by Django 3.1.2 on 2020-11-04 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_category', to='news.postcategorymodel', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(related_name='post_tags', to='news.PostTagModel', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='pinnedpostmodel',
            name='pinned_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_posts', to='news.postmodel', verbose_name='Post'),
        ),
    ]
