# Generated by Django 3.1.2 on 2020-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=18, verbose_name='Phone number')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='SiteMainSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=18, verbose_name='Site title')),
                ('description', models.TextField(verbose_name='Site description')),
                ('description_ru', models.TextField(null=True, verbose_name='Site description')),
                ('description_en', models.TextField(null=True, verbose_name='Site description')),
                ('logo_1_image', models.ImageField(upload_to='images/settings', verbose_name='Site logo image')),
                ('logo_2_image', models.ImageField(upload_to='images/settings', verbose_name='Site alternative logo image')),
                ('user_avatar', models.ImageField(upload_to='images/settings', verbose_name='Default user avatar')),
                ('guest_avatar', models.ImageField(upload_to='images/settings', verbose_name='Default guest avatar')),
                ('deleted_avatar', models.ImageField(upload_to='images/settings', verbose_name='Deleted avatar')),
            ],
            options={
                'verbose_name': 'Main settings',
                'verbose_name_plural': 'Main settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSocialNetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=18, unique=True, verbose_name='Social net')),
                ('url', models.URLField(verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='images/settings/social', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Social net',
                'verbose_name_plural': 'Social nets',
                'ordering': ['title'],
            },
        ),
    ]
